require:
  - solidus_dev_support/rubocop

inherit_gem:
  solidus_dev_support: .rubocop.yml

AllCops:
  NewCops: enable
  Exclude:
    - spec/dummy/**/*
    - vendor/**/*

Rails/SkipsModelValidations:
  Exclude:
    - db/migrate/**/*

Gemspec/OrderedDependencies:
  Enabled: false

Style/RegexpLiteral:
  Enabled: false

Style/MissingRespondToMissing:
  Enabled: false

RSpec/NamedSubject:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

Lint/EmptyBlock:
  Enabled: false

Lint/EmptyFile:
  Enabled: false

Style/RescueStandardError:
  Enabled: false

RSpec/PredicateMatcher:
  Enabled: false

RSpec/AnyInstance:
  Enabled: false
